# Generated by Django 5.0.7 on 2026-06-15 11:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_fee_versioning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ['name', '-effective_date', '-version'], 'verbose_name': '费用类型', 'verbose_name_plural': '费用类型'},
        ),
        migrations.AlterField(
            model_name='feetype',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='建筑面积'),
        ),
    ]
